nohup: ignoring input
[I 2024-10-18 02:00:57.859 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-10-18 02:00:57.866 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-10-18 02:00:57.874 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-10-18 02:00:57.876 ServerApp] Writing Jupyter server cookie secret to /config/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-10-18 02:00:58.377 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-10-18 02:00:58.396 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-10-18 02:00:58.399 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-10-18 02:00:58.402 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-10-18 02:00:58.404 LabApp] JupyterLab extension loaded from /config/workspace/jupyterlab-venv/lib/python3.10/site-packages/jupyterlab
[I 2024-10-18 02:00:58.404 LabApp] JupyterLab application directory is /config/workspace/jupyterlab-venv/share/jupyter/lab
[I 2024-10-18 02:00:58.405 LabApp] Extension Manager is 'pypi'.
[I 2024-10-18 02:00:58.410 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-10-18 02:00:58.410 ServerApp] Serving notebooks from local directory: /config/workspace
[I 2024-10-18 02:00:58.410 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2024-10-18 02:00:58.410 ServerApp] http://d73711a8ee52:8888/lab?token=cfd4661e078240f4ce8af5b90a59ebd591314006302ffe18
[I 2024-10-18 02:00:58.410 ServerApp]     http://127.0.0.1:8888/lab?token=cfd4661e078240f4ce8af5b90a59ebd591314006302ffe18
[I 2024-10-18 02:00:58.410 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-10-18 02:00:58.416 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///config/.local/share/jupyter/runtime/jpserver-12431-open.html
    Or copy and paste one of these URLs:
        http://d73711a8ee52:8888/lab?token=cfd4661e078240f4ce8af5b90a59ebd591314006302ffe18
        http://127.0.0.1:8888/lab?token=cfd4661e078240f4ce8af5b90a59ebd591314006302ffe18
[I 2024-10-18 02:00:58.454 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-10-18 02:01:30.399 LabApp] Could not determine jupyterlab build status without nodejs
[I 2024-10-18 02:01:38.593 ServerApp] Writing notebook-signing key to /config/.local/share/jupyter/notebook_secret
[W 2024-10-18 02:01:38.595 ServerApp] Notebook C4_W4_Assignment_2.ipynb is not trusted
[I 2024-10-18 02:01:39.148 ServerApp] Kernel started: 21c36d71-1a4a-4b78-8c98-2a005a6ba050
[I 2024-10-18 02:01:39.800 ServerApp] Connecting to kernel 21c36d71-1a4a-4b78-8c98-2a005a6ba050.
[I 2024-10-18 02:01:39.860 ServerApp] Connecting to kernel 21c36d71-1a4a-4b78-8c98-2a005a6ba050.
[I 2024-10-18 02:01:39.923 ServerApp] Connecting to kernel 21c36d71-1a4a-4b78-8c98-2a005a6ba050.
[I 2024-10-18 02:35:40.952 ServerApp] Saving file at /C4_W4_Assignment_2.ipynb
[I 2024-10-18 02:37:41.088 ServerApp] Saving file at /C4_W4_Assignment_2.ipynb
[E 2024-10-18 02:48:28.286 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/tornado/web.py", line 1753, in _execute
        raise HTTPError(405)
    tornado.web.HTTPError: HTTP 405: Method Not Allowed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/tornado/web.py", line 1298, in send_error
        self.write_error(status_code, **kwargs)
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 739, in write_error
        html = self.render_template("%s.html" % status_code, **ns)
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 665, in render_template
        ns.update(self.template_namespace)
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 675, in template_namespace
        logged_in=self.logged_in,
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 198, in logged_in
        user = self.current_user
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/tornado/web.py", line 1424, in current_user
        self._current_user = self.get_current_user()
      File "/config/workspace/jupyterlab-venv/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 177, in get_current_user
        raise RuntimeError(msg)
    RuntimeError: Calling `Template404.get_current_user()` directly is deprecated in jupyter-server 2.0. Use `self.current_user` instead (works in all versions).
[W 2024-10-18 02:48:28.294 ServerApp] 405 CONNECT cloudflare.com:443 (@179.43.133.162) 8.40ms referer=None
[I 2024-10-18 03:37:46.472 ServerApp] Saving file at /C4_W4_Assignment_2.ipynb
[I 2024-10-18 03:46:48.510 ServerApp] 302 GET / (@198.235.24.146) 0.54ms
